spring:
    application:
        name: smsService
    jpa:
        open-in-view: true
        properties:
            hibernate:
              show_sql: true
        hibernate:
            ddl-auto: none
    datasource:
        url: jdbc:mysql://db_smsservice:3350/smsservice?useUnicode=true&allowPublicKeyRetriaval=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
        username: root
        password: root
        hikari:
            minimum-idle: 1
            maximum-pool-size: 50
            pool-name: smsApplicationPool
            maxLifetime:  2000000
            idleTimeout:  30000
            connectionTimeout:  30000

kafka:
    consumer:
        bootstrap: localhost:9092
        group: WorkUnitApp
        topic: sms


server:
    port: 8088





