version: "3.8"
services:
   db_cart:
    image: mysql:latest
    container_name: db_cart
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cart
      - MAX_CONNECTIONS=500
    ports:
      - 3350:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8 --explicit_defaults_for_timestamp


   db_smsservice:
    image: mysql:latest
    container_name: db_smsservice
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=smsservice
      - MAX_CONNECTIONS=500
    ports:
      - 3360:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8 --explicit_defaults_for_timestamp

   zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
   kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

   smsservice:
    restart: on-failure
    container_name: smsserivce
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_smsservice:3360/smsservice?useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8&useSSL=false
    links:
      - db_smsservice
      - zookeeper
      - kafka
    build:
      context: ./smsservice
      dockerfile: Dockerfile
    command: bash -c "
      mvn clean install -DskipTests
      && cp target/smsservice*.jar app.jar
      && java -jar app.jar
      "
    ports:
      - "8088:8088"
    volumes:
      - "${HOME}/.m2/:/root/.m2/"
    depends_on:
      - db_smsservice
      - zookeeper
      - kafka

   cartmanagement:
    restart: on-failure
    container_name: cartmanagement
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_cart:3350/cart?useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8&useSSL=false
    links:
      - db_cart
      - zookeeper
      - kafka
    build:
      context: ./cartmanagement
      dockerfile: Dockerfile
    command: bash -c "
      mvn clean install -DskipTests
       && cp target/car*.jar app.jar
      && java -jar app.jar
     "
    ports:
      - "8087:8087"
    volumes:
      - "${HOME}/.m2/:/root/.m2/"
    depends_on:
      - db_cart
      - zookeeper
      - kafka